# Generated by Django 3.0 on 2023-02-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable('Address', 'lettings_address'),
                migrations.AlterModelTable('Letting', 'lettings_letting'),
                migrations.AlterModelTable('Profile', 'profiles_profile'),
            ],

            state_operations=[
                migrations.DeleteModel('Address'),
                migrations.DeleteModel('Letting'),
                migrations.DeleteModel('Profile'),
            ]

        )
    ]
